#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "BitmapFontGenerator.h"

int main(int argc, char **argv)
{
  FILE *in, *out;
  puts("Debug: StartupValidate");
  StartupValidate(argc, argv); 
   
  puts("Debug: OpenFiles");
  OpenFiles(&in, argv[1], &out, argv[2]);

  puts("Debug: WriteHeaderComment");
  WriteHeaderComment(out);

  puts("Debug: WritePreProcessors");
  WritePreProcessors(out);
  
  puts("Debug: WriteCharArrayExpression");
  WriteCharArrayExpression(out, in, argv[3], argv[4]);

  puts("Debug: WritePreProcessorUndefineExpression");
  WritePreProcessorUndefineExpression(out);

  CloseFiles(in, out);
  
  return 0;
}

void StartupValidate(int argc, char** argv)
{
  if (argc != 5) {
    puts("usage>makefont [source.txt] [font.bin] [bitmap name] [bitmap size]");
    exit(-1);
  }

  return;
}

void OpenFiles(FILE **in, char *inpath, FILE **out, char *outpath)
{
  *in = fopen(inpath, "rb");
  *out = fopen(outpath, "wb");

  if (in == NULL) {
    puts("can't open input file.");
    exit(-1);
  }

  if (out == NULL) {
    puts("can't open output file.");
    exit(-2);
  }
}


void CloseFiles(FILE *in, FILE *out)
{
  fclose(in);
  fclose(out);

  return;
}

void RemoveSpecialChars(char *src, int length)
{
  char *p = src;
  for (int i = 0; i < length; i++)
  {
    switch (*p++)
    {
      case '\t':
      case '\n':
      case '\r':
      case '\v':
      case '\f':
      *p = ' ';
    }
  }
  return;
}

void WritePreProcessors(FILE *out)
{
  fputs("#define X )*2+1\n", out);
  fputs("#define _ )*2\n", out);
  fputs("#define s ((((((((0\n", out);

  return;
}

void WriteHeaderComment(FILE *out)
{
  fputs("/*\n  This file was generated by the code generator. \n", out);
  fputs("  Changing the content manually may result in loss of changes. \n", out);
  fputs("  The code generator recommends using auto generation after changing the seed file.\n */ \n\n", out);

  return;
}

void WriteCharArrayExpression(FILE *out, FILE* in, char *bmapName, char *bmapSize)
{
  int bmapSizeNum;

  WriteArrayBeginExpression("char", bmapName, bmapSize, out);

  int i = 1;
  char s[12];
  while (fgets(s, 12, in) != NULL)
  {
    RemoveSpecialChars(s, 12);
    
    if (strstr(s, "char") != NULL)
    {
      WriteCommentoutText(s, out);
    }
    else if (strlen(s) == 10)
    {

      WriteBitmapText(s, out);

      bmapSizeNum = (int)strtol(bmapSize, NULL, 10);
      WriteElementEndExpression(i, bmapSizeNum, out);

      i += 1;
    }
  }

  WriteArrayEndExpression(out);

  return;
}
void WritePreProcessorUndefineExpression(FILE *out)
{
  fputs("#undef X\n", out);
  fputs("#undef _\n", out);
  fputs("#undef s\n", out);

  return;
}

void WriteCommentoutText(char *str, FILE *out)
{
  fputs("\n/*", out);
  fputs(str, out);
  fputs("*/\n", out);

  return;
}

void WriteBitmapText(char *str, FILE *out)
{
  fputs("s   ", out);
  for (int j = 0; j < 10; j++)
  {
    if (str[j] == '*')
    {
      fputc('X', out);
      fputc(' ', out);
    }
    else if (str[j] == '.')
    {
      fputc('_', out);
      fputc(' ', out);
    }
  }

  return;
}

void WriteArrayBeginExpression(char *elementType, char *arrayName, char* arraySize, FILE *out)
{
  fputs("\n", out);
  fputs(elementType , out);
  fputc(' ', out);
  fputs(arrayName, out);
  fputc('[', out);
  fputs(arraySize, out);
  fputs("] = {\n", out);

  return;
}

void WriteArrayEndExpression(FILE *out)
{
  fputs("};\n", out);
  fputs("\n", out);

  return;
}

void WriteElementEndExpression(int currentIdx, int length, FILE *out)
{
  if (currentIdx != length)
  {
    fputs("  ,\n", out);
  }
  else
  {
    fputc('\n', out);
  }

  return;
}
